version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ydiskhelper
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/ydiskhelper/logs
      - ./media:/ydiskhelper/media
      - ./staticfiles:/ydiskhelper/staticfiles
    env_file:
      - .env