services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ydh_demo
    expose:
      - 8000
    volumes:
      - ./logs:/ydiskhelper/logs
      - ./media:/ydiskhelper/media
      - ./staticfiles:/ydiskhelper/staticfiles
    user: "1001:1001"
    env_file:
      - .env
    networks:
      - ydh_network

networks:
  ydh_network:
    external: true
    name: ydh_network