services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ydh_demo
    expose:
      - 8000
    volumes:
      - type: bind
        source: ./logs
        target: /ydiskhelper/logs
        volume:
          nocopy: true
      - type: bind
        source: ./media
        target: /ydiskhelper/media
        volume:
          nocopy: true
      - type: bind
        source: ./staticfiles
        target: /ydiskhelper/staticfiles
        volume:
          nocopy: true
    user: "1001:1001"
    env_file:
      - .env
    networks:
      - ydh_network

networks:
  ydh_network:
    external: true
    name: ydh_network